### ISSUE TITLE
Question about reproduction

### ISSUE THREAD

**Issue by tyshiwo1** [JingweiJ/ActionGenome#12]
When I reproduce the results, I find that the PredClS is really high, although I use the random predicate score. Is my own problem or the dataset's ?

**Comment by zoezhou1999** [comment]
Hi, I am also reproducing the results. Can we have a discussion? Thank you. @tyshiwo1 
My email is 3160104220@zju.edu.cn

**Comment by aa200647963** [comment]
大哥，我也想复现这个结果，能不能讨论下 邮箱 200647963@qq.com

**Comment by aa200647963** [comment]
大哥，我也想复现这个结果，能不能讨论下 邮箱 200647963@qq.com @tyshiwo1  @zoezhou1999

**Comment by forbiddenname** [comment]
Hi, Have you solved this problem?
