### ISSUE TITLE
Annotation with None

### ISSUE THREAD

**Issue by raghavgoyal14** [JingweiJ/ActionGenome#4]
Thank you for providing the annotations!
There are quite a lot of `None` object annotations, for e.g.

```
{'attention_relationship': None,
 'bbox': None,
 'class': 'sofa/couch',
 'contacting_relationship': None,
 'metadata': {'set': 'test', 'tag': 'BLLCM.mp4/sofa_couch/000394'},
 'spatial_relationship': None,
 'visible': False}
```
Are these annotations to be ignored?

**Comment by JingweiJ** [comment]
Hi @raghavgoyal14 , 'none' means that there's no available annotations in this frame, mostly because that the interacted object is invisible.

**Comment by raghavgoyal14** [comment]
Ok, Thanks.

**Comment by xiaodanhu** [comment]
Hi @raghavgoyal14 , is the 'None' the same as the relationship label "unsure"? Thanks
